# Generated by Django 2.2.1 on 2019-05-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw_21', '0003_auto_20190528_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='hobbie',
            field=models.ManyToManyField(related_name='person', to='cw_21.Hobbie'),
        ),
    ]
